### ISSUE TITLE
Naming issue in utensor_cgen

### ISSUE THREAD

**Issue by hahmed-and** [uTensor/utensor_cgen#124] opened 2020-10-12 13:35 UTC
The generated model code had around 51 errors where instead of writing for example t_sequential_1dense_9BiasAddReadVariableOpresource0 it would write t_sequential_1dense_9;BiasAddReadVariableOpresource0 so I had to remove the ; in each Tensor name.

**Comment by dboyliao** [comment] 2020-10-12 14:30
@hahmed-and Thanks for opening the issue.
Would you mind to provide me a model file so I can inspect and pin down the root cause of the issue?

**Comment by dboyliao** [comment] 2020-10-12 14:31
You can send me the model file on Slake if you don't want it to be in the public domain.

**Comment by hahmed-and** [comment] 2020-10-12 14:52
Hello I've sent it on DM of slackbox.

**Comment by dboyliao** [comment] 2020-10-28 14:15
Fixed by #125, closing this issue

**Closed by dboyliao** 2020-10-28 14:15 UTC
